INSERT INTO Actors (firstname, lastname, bio, rating) VALUES
('Marlon', 'Brando', 'Legendary American actor.', 9.5),
('Al', 'Pacino', 'Known for The Godfather and Scarface.', 9.4),
('Robert', 'De Niro', 'Famous for Taxi Driver and Raging Bull.', 9.3),
('Leonardo', 'DiCaprio', 'Oscar-winning actor.', 9.1),
('Tom', 'Hanks', 'Beloved for Forrest Gump and Cast Away.', 9.0),
('Brad', 'Pitt', 'Known for Fight Club and Troy.', 8.9),
('Johnny', 'Depp', 'Famous for Pirates of the Caribbean.', 8.7),
('Morgan', 'Freeman', 'Known for Shawshank Redemption.', 9.2),
('Denzel', 'Washington', 'Two-time Oscar winner.', 9.1),
('Anthony', 'Hopkins', 'Best known for Hannibal Lecter.', 9.0),
('Matt', 'Damon', 'Known for The Bourne series.', 8.8),
('Christian', 'Bale', 'Oscar-winning method actor.', 9.0),
('Harrison', 'Ford', 'Star Wars and Indiana Jones.', 8.7),
('Samuel', 'Jackson', 'Known for Pulp Fiction.', 8.6),
('Jack', 'Nicholson', 'Legendary career, The Shining.', 9.3),
('Heath', 'Ledger', 'Posthumous Oscar for Joker.', 9.2),
('Russell', 'Crowe', 'Known for Gladiator.', 8.8),
('Keanu', 'Reeves', 'The Matrix and John Wick.', 8.7),
('Chris', 'Hemsworth', 'Known for Thor.', 8.5),
('Chris', 'Evans', 'Captain America star.', 8.4),
('Scarlett', 'Johansson', 'Black Widow and Lost in Translation.', 8.6),
('Natalie', 'Portman', 'Oscar for Black Swan.', 8.7),
('Anne', 'Hathaway', 'Known for Les Misérables.', 8.5),
('Meryl', 'Streep', 'Record-breaking Oscar nominee.', 9.5),
('Julia', 'Roberts', 'Pretty Woman star.', 8.4),
('Charlize', 'Theron', 'Oscar-winning actress.', 8.8),
('Emma', 'Stone', 'Oscar for La La Land.', 8.6),
('Jennifer', 'Lawrence', 'Hunger Games star.', 8.5),
('Kate', 'Winslet', 'Titanic and Eternal Sunshine.', 8.9),
('Nicole', 'Kidman', 'Versatile actress.', 8.7),
('Hugh', 'Jackman', 'Wolverine in X-Men.', 8.6),
('Ryan', 'Gosling', 'Known for Drive and La La Land.', 8.7),
('Mark', 'Ruffalo', 'Hulk in Avengers.', 8.3),
('Jeremy', 'Renner', 'Known for Hurt Locker.', 8.2),
('Tom', 'Cruise', 'Mission Impossible star.', 8.7),
('Will', 'Smith', 'Men in Black and Pursuit of Happyness.', 8.5),
('Chris', 'Pratt', 'Star-Lord in Guardians.', 8.3),
('Paul', 'Rudd', 'Ant-Man star.', 8.2),
('Benedict', 'Cumberbatch', 'Doctor Strange star.', 8.8),
('Cillian', 'Murphy', 'Known for Peaky Blinders.', 8.7),
('Florence', 'Pugh', 'Rising star in Hollywood.', 8.5),
('Zendaya', 'Coleman', 'Euphoria and Spider-Man.', 8.6),
('Timothée', 'Chalamet', 'Star of Dune and Call Me By Your Name.', 8.7),
('Daniel', 'Day-Lewis', 'Three-time Oscar winner.', 9.6),
('Gary', 'Oldman', 'Oscar-winning actor.', 9.0),
('Joaquin', 'Phoenix', 'Oscar for Joker.', 9.1),
('Michael', 'Fassbender', 'Known for X-Men.', 8.6),
('Idris', 'Elba', 'Versatile British actor.', 8.5),
('Andrew', 'Garfield', 'Known for Spider-Man.', 8.4),
('Adam', 'Driver', 'Star Wars and Marriage Story.', 8.6);

